//! Generates JS shims and HTML shells for loading WASM in Chrome extensions.

use crate::source_parser::ExtensionMetadata;

pub fn generate_background_js(metadata: &ExtensionMetadata, crate_name: &str) -> String {
    let wasm_name = crate_name.replace('-', "_");

    let mut exports = Vec::new();
    for bg in &metadata.background_functions {
        exports.push(format!("__oxichrome_bg_{bg}"));
    }
    for handler in &metadata.event_handlers {
        exports.push(format!("__oxichrome_register_{}", handler.fn_name));
    }

    let imports = if exports.is_empty() {
        String::new()
    } else {
        format!(", {{ {} }}", exports.join(", "))
    };

    let mut init_calls = String::new();
    for handler in &metadata.event_handlers {
        let fn_name = &handler.fn_name;
        init_calls.push_str(&format!("    __oxichrome_register_{fn_name}();\n"));
    }
    for bg in &metadata.background_functions {
        init_calls.push_str(&format!("    __oxichrome_bg_{bg}();\n"));
    }

    format!(
        r#"// Auto-generated by oxichrome. Do not edit.
import init{imports} from './wasm/{wasm_name}.js';

async function start() {{
    try {{
        await init();
{init_calls}        console.log('[oxichrome] Background service worker initialized.');
    }} catch (e) {{
        console.error('[oxichrome] Failed to initialize WASM:', e);
    }}
}}

start();
"#
    )
}

pub fn generate_popup_html() -> String {
    r#"<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>html, body { margin: 0; padding: 0; min-width: 240px; min-height: 120px; }</style>
</head>
<body>
<script type="module" src="popup.js"></script>
</body>
</html>
"#
    .to_string()
}

pub fn generate_popup_js(crate_name: &str) -> String {
    let wasm_name = crate_name.replace('-', "_");

    format!(
        r#"// Auto-generated by oxichrome. Do not edit.
import init, {{ __oxichrome_mount_popup }} from './wasm/{wasm_name}.js';

try {{
    await init();
    __oxichrome_mount_popup();
}} catch (e) {{
    console.error('[oxichrome] Popup init failed:', e);
    document.body.textContent = 'Error: ' + e.message;
}}
"#
    )
}

pub fn generate_options_html() -> String {
    r#"<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>html, body { margin: 0; padding: 0; }</style>
</head>
<body>
<script type="module" src="options.js"></script>
</body>
</html>
"#
    .to_string()
}

pub fn generate_options_js(crate_name: &str) -> String {
    let wasm_name = crate_name.replace('-', "_");

    format!(
        r#"// Auto-generated by oxichrome. Do not edit.
import init, {{ __oxichrome_mount_options }} from './wasm/{wasm_name}.js';

try {{
    await init();
    __oxichrome_mount_options();
}} catch (e) {{
    console.error('[oxichrome] Options init failed:', e);
    document.body.textContent = 'Error: ' + e.message;
}}
"#
    )
}

pub fn generate_content_script_js(fn_name: &str, crate_name: &str) -> String {
    let wasm_name = crate_name.replace('-', "_");
    let wrapper_name = format!("__oxichrome_cs_{fn_name}");

    format!(
        r#"// Auto-generated by oxichrome. Do not edit.
// Content script: {fn_name}
(async () => {{
    try {{
        const src = chrome.runtime.getURL('wasm/{wasm_name}.js');
        const wasm = await import(src);
        await wasm.default();
        wasm.{wrapper_name}();
        console.log('[oxichrome] Content script "{fn_name}" initialized.');
    }} catch (e) {{
        console.error('[oxichrome] Content script "{fn_name}" failed to initialize:', e);
    }}
}})();
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source_parser::EventHandler;

    #[test]
    fn test_background_js_es_module() {
        let metadata = ExtensionMetadata {
            name: Some("Test".to_string()),
            version: Some("1.0.0".to_string()),
            description: None,
            key: None,
            permissions: vec![],
            host_permissions: vec![],
            background_functions: vec!["start".to_string()],
            event_handlers: vec![EventHandler {
                fn_name: "handle_install".to_string(),
                namespace: "runtime".to_string(),
                event_name: "on_installed".to_string(),
            }],
            has_popup: false,
            has_options_page: false,
            content_scripts: vec![],
        };

        let js = generate_background_js(&metadata, "counter-extension");
        assert!(js.contains(
            "import init, { __oxichrome_bg_start, __oxichrome_register_handle_install }"
        ));
        assert!(js.contains("from './wasm/counter_extension.js'"));
        assert!(js.contains("await init();"));
        assert!(js.contains("__oxichrome_register_handle_install();"));
        assert!(js.contains("__oxichrome_bg_start();"));
    }

    #[test]
    fn test_popup_html() {
        let html = generate_popup_html();
        assert!(html.contains("src=\"popup.js\""));
        assert!(html.contains("min-width: 240px"));
        assert!(!html.contains("import init"));
    }

    #[test]
    fn test_popup_js() {
        let js = generate_popup_js("counter-extension");
        assert!(js.contains("__oxichrome_mount_popup"));
        assert!(js.contains("counter_extension.js"));
        assert!(js.contains("await init();"));
    }

    #[test]
    fn test_options_html() {
        let html = generate_options_html();
        assert!(html.contains("src=\"options.js\""));
        assert!(!html.contains("import init"));
    }

    #[test]
    fn test_options_js() {
        let js = generate_options_js("my-ext");
        assert!(js.contains("__oxichrome_mount_options"));
        assert!(js.contains("my_ext.js"));
        assert!(js.contains("await init();"));
    }

    #[test]
    fn test_content_script_js() {
        let js = generate_content_script_js("inject", "my-extension");
        assert!(js.contains("chrome.runtime.getURL('wasm/my_extension.js')"));
        assert!(js.contains("__oxichrome_cs_inject"));
        assert!(js.contains("await wasm.default()"));
        assert!(js.contains("Content script \"inject\" initialized."));
        // Must NOT start with a static import statement
        assert!(!js.starts_with("import"));
    }
}
